changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

packageExtensions:
  istanbul-lib-processinfo@*:
    dependencies:
      mkdirp: "*"
  tcompare@*:
    dependencies:
      diff: "*"
  treport@*:
    dependencies:
      tap-yaml: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
